"""Added specializations

Revision ID: bacddca12f75
Revises: 754847204cad
Create Date: 2025-02-27 16:09:31.681424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bacddca12f75'
down_revision: Union[str, None] = '754847204cad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specializations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('short_description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_specializations_id'), 'specializations', ['id'], unique=False)
    op.create_table('profile_specialization',
    sa.Column('profile_id', sa.String(), nullable=False),
    sa.Column('specialization_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['specialization_id'], ['specializations.id'], ),
    sa.PrimaryKeyConstraint('profile_id', 'specialization_id')
    )
    op.add_column('profiles', sa.Column('location', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('picture', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'picture')
    op.drop_column('profiles', 'location')
    op.drop_table('profile_specialization')
    op.drop_index(op.f('ix_specializations_id'), table_name='specializations')
    op.drop_table('specializations')
    # ### end Alembic commands ###
